### ISSUE TITLE
Is this module compatible with the new @use syntax?

### ISSUE THREAD

**Issue by poespas** [fylgja/fylgja-utilkit#4]
Is this moduel compitable with the new @use syntax that recently got introduced?

More info https://sass-lang.com/documentation/at-rules/use

And if so, is it possible to update the docs for this?

**Comment by GrimLink** [comment]
I will update the docs for the new function library found here -> https://github.com/fylgja/fylgja-sass (`@fylgja/sass`).
You kan use this package in a the newer sass syntax but I will not update this package it since it will be replace by the newer `@fylgja/utilpack` and `@fylgja/sass`.
